# Generated by Django 6.0.8 on 2026-09-22 11:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_nameguard', '0004_sitecode_location_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renamelog',
            name='batch_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
