# Generated by Django 6.0.8 on 2026-09-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_nameguard', '0005_alter_renamelog_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecode',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
