# Generated by Django 6.0.8 on 2026-09-24 03:35

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0241_nullify_empty_cable_end'),
        ('extras', '0140_imageattachment_image_size'),
        ('netbox_nameguard', '0007_atolltype_facilitytype_islandtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='renamelog',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nameguard_rename_logs', to='dcim.rack'),
        ),
        migrations.CreateModel(
            name='RackNamingPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(default='Default', max_length=50)),
                ('template', models.CharField(max_length=100)),
                ('seq_width', models.PositiveSmallIntegerField(default=2)),
                ('seq_policy', models.CharField(default='always_increment', max_length=30)),
                ('comments', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Rack Naming Pattern',
                'verbose_name_plural': 'Rack Naming Patterns',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
